### ISSUE TITLE
Cannot Migrate Contracts

### ISSUE THREAD

**Issue by amorriscode** [daostack/DAOstack-Hackers-Kit#19]
When running `npm run launch-local`, I get an error during the truffle migrate step.

It looks like `DaoCreator.forgeOrg` is running out of gas. I am trying to configure truffle to increase the gas but have yet to reach success. 😢 

```
2_deploy_dao.js
===============
Arc.js (error): ContractWrapperBase.wrapTransactionInvocation: An error occurred calling DaoCreator.forgeOrg: Error: VM Exception while processing transaction: revert
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:38:16)
    at /Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/web3/lib/web3/httpprovider.js:129:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/amorris2/Desktop/DAOstack-Hackers-Kit/starter-template/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

I noticed someone mentioned something similar on the [arc.js repo](https://github.com/daostack/arc.js/issues/128).

**Comment by amorriscode** [comment]
According to @ben-kaufman, as per a discussion on Discord, the team has moved the stack to use a new tool to migrate their contracts. It seems there is an incompatibility with the example in the kit.

**Comment by crazyrabbitLTC** [comment]
I am getting this error as well. @amorriscode do you have any more information regarding this conversation on Discord? Does anyone have a suggestion on how to try running the starter kit?

**Comment by amorriscode** [comment]
@crazyrabbitLTC No, sorry. Maybe @ben-kaufman can help you as I have abandoned my attempts of using the stack.

**Comment by shivgupt** [comment]
@crazyrabbitLTC For now if you move to `remove-arcjs-dep` branch the `starter-template` project has updated documentation and scripts for running the sample project.
We are working on updating the examples in Hacker-kit.

**Comment by shivgupt** [comment]
Closing this issue because all examples are updated to use latest migration tools and now it works
